spring:
    application:
        name: ec4BIT - Connector
    profiles:
        active: development

envirocar:
    url: http://envirocar.org/api/stable

bigiot:
    marketplace: 
        url:  https://market.big-iot.org

---

spring:
    profiles: development
bigiot:
    provider:
        address: localhost
        port: 7777
    applications: 
        speedvalues:
            local_id: Traffic_Driving_Speed_Values
            name: Traffic Driving Speed Values
            route: speedvalues
            expireDate: 2018-02-28T01:23:45
        measurements:
            local_id: Traffic_Driving_Measurements
            name: Traffic Driving Measurements
            route: measurements
            expireDate: 2018-02-28T01:23:45
        tracks:
            local_id: Traffic_Driving_Tracks
            name: Traffic Driving Tracks
            route: tracks
            expireDate: 2018-02-28T01:23:45

---

spring:
    profiles: productive
bigiot:
    provider:
        address: processing.envirocar.org
        port: 8081
    applications:
        speedvalues:
            local_id: ec-speed-offering
            name: enviroCar Speed Values
            route: speedvalues
            expireDate: 2018-02-28T01:23:45
        measurements:
            local_id: ec-measurements-offering
            name: enviroCar Measurements
            route: measurements
            expireDate: 2018-02-28T01:23:45
        tracks:
            local_id: ec-tracks-offering
            name: enviroCar Tracks
            route: tracks
            expireDate: 2018-02-28T01:23:45
