spring.application.name: Connector

ec4bit:
    contact: envirocar@52north.org

envirocar:
    url: http://envirocar.org/api/stable

bigiot:
    marketplace: 
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7777
    applications:
        speeddata:
            local_id: speed-offering
            name: Traffic Speed Values
            route: speedvalues
            
            
