spring.application.name: Connector

ec4bit:
    contact: envirocar@52north.org

envirocar:
    url: http://envirocar.org/api/stable

bigiot:
    marketplace: 
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7777
    applications:
        speed_data:
            local_id: speed-offering
            name: Driving Speed Values
            route: speedvalues
        driving_data:
            local_id: driving-offering
            name: Traffic Driving Measurements
            route: measurements