spring.application.name: Connector

ec4bit:
    contact: envirocar@52north.org

envirocar:
    url: http://envirocar.org/api/stable

bigiot:
    marketplace: 
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7777
    applications:
        speed_data:
            local_id: speed-offering
            name: TEST Driving Speed Values
            route: speedvalues
        driving_data:
            local_id: driving-offering
            name: TEST Traffic Driving Measurements
            route: measurements
        track_data:
            local_id: track-offering
            name: TEST Driving Tracks
            route: tracks
        single_track_data:
            local_id: single-track-offering
            name: TEST Driving Track
            route: track
        segments_data:
            local_id: segments-offering
            name: TEST Traffic Driving Segments
            route: segments
#server:
#    port: 8081
    
#logging:
    # path: /var/lib/ec4BIT/logs
#     path: logs