spring:
    application:
        name: ec4BIT - Connector
    profiles:
        active: development

ec4bit:
    contact: envirocar@52north.org

envirocar:
    url: http://envirocar.org/api/stable

bigiot:
    marketplace: 
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7777

---

spring:
    profiles: development
bigiot:
    provider:
        address: localhost
        port: 7777
    applications: 
        speed_data:
            local_id: test-speed-offering
            name: (enviroCar Testing) / Driving Speed Values
            route: speedvalues
        driving_data:
            local_id: test-measurements-offering
            name: (enviroCar Testing) / Traffic Driving Measurements
            route: measurements
        track_data:
            local_id: test-track-offering
            name: (enviroCar Testing) / Driving Tracks
            route: tracks
        single_track_data:
            local_id: test-single-track-offering
            name: (enviroCar Testing) / Driving Track
            route: track

---

spring:
    profiles: productive
bigiot:
    provider:
        address: processing.envirocar.org
        port: 8081
    applications:
        speed_data:
            local_id: speed-offering
            name: Driving Speed Values
            route: speedvalues
        driving_data:
            local_id: measurements-offering
            name: Traffic Driving Measurements
            route: measurements
        track_data:
            local_id: tracks-offering
            name: Driving Tracks
            route: tracks
        single_track_data:
            local_id: single-track-offering
            name: Driving Track
            route: track